names = ["andy","duke","lily","tom"]
print("I will invate "+ names[0] +" to join my party.")
print("I will invate "+ names[1] +" to join my party.")
print("I will invate "+ names[2] +" to join my party.")
print("I will invate "+ names[3] +" to join my party.")
print(names[3]+" can't join us.")
names[3] = "mary"
print(names[3] +" will join us.")
print("I will invate "+ names[0] +" to join my party.")
print("I will invate "+ names[1] +" to join my party.")
print("I will invate "+ names[2] +" to join my party.")
print("I will invate "+ names[3] +" to join my party.")
print("I find a bigger table.")
names.insert(0,"fake")
names.insert(2,"taylor")
names.append("wiki")
print("I will invate "+ names[0] +" to join my party.")
print("I will invate "+ names[1] +" to join my party.")
print("I will invate "+ names[2] +" to join my party.")
print("I will invate "+ names[3] +" to join my party.")
print("I will invate "+ names[4] +" to join my party.")
print("I will invate "+ names[5] +" to join my party.")
print("I will invate "+ names[6] +" to join my party.")
print("It's so unfortunately I can only invate two people.")
out1=names.pop()
print("sorry to "+out1)
out2=names.pop()
print("sorry to "+out2)
out3=names.pop()
print("sorry to "+out3)
out4=names.pop()
print("sorry to "+out4)
out5=names.pop()
print("sorry to "+out5)
print(names[0]+" are still in the list.")
print(names[1]+" are still in the list.")
del names[0]
del names[0]
print(names)

